######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 4 14:19:47 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += widj.ui
SOURCES += main.cpp view.cpp
