######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 4 14:50:34 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += view.h
FORMS += widj.ui
SOURCES += main.cpp view.cpp
